import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";

import { AppSidebar } from "@/components/app-sidebar";
import ScrollbarProgress from "@/components/component/scrollbar-progress";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import "./globals.css";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${notoSans.className} container mx-auto antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <AppSidebar />
            <main className="relative w-full">
              <ScrollbarProgress />
              <SidebarTrigger className="sticky top-0" />
              <div className="mx-auto px-4 py-12 md:px-24 xl:px-40">
                {children}
              </div>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
